### ISSUE TITLE
怎么运行啊，这是什么框架的

### ISSUE THREAD

**Issue by jebai0521** [huyinghuan/lottery#1]

**Comment by huyinghuan** [comment]
哦， 基于express的框架， 其中 ORM和路由用了自己写的 coal和water-pit.
运行比较简单,首先这是node所以需要nodejs环境， 
clone 下来后， 进去根目录运行  按照依赖包
```
npm install 
```

然后运行还需要运行
```
npm install coffee-script -g
npm install node-dev
```
上面都是安装环境。
运行的话可以用
```
node-dev server/src/index.coffee
```
然后打开浏览器 localhost:3000 即可。

ps：这个程序会在下周2之前完成，可以到时候在关注一下。因为公司年会在周三 （^ _ ^）

**Comment by huyinghuan** [comment]
已完成！
